sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_8dc30029196d_key -iv $encrypted_8dc30029196d_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project gcp-course-290519
  - gcloud config set compute/zone  us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t hedleygois/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hedleygois/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master

# language: generic
# sudo: required
# services:
#   - docker

# before_install:
#   - docker build -t hedleygois/multi-docker-course-test -f ./client/Dockerfile.dev ./client/

# script:
#   - docker run hedleygois/multi-docker-course-test -e CI=true hedleygois/multi-docker-course-test npm test

# after_success:
#   - docker build -t hedleygois/multi-docker-course-client ./client
#   - docker build -t hedleygois/multi-docker-course-nginx ./nginx
#   - docker build -t hedleygois/multi-docker-course-server ./server
#   - docker build -t hedleygois/multi-docker-course-worker ./worker
#   - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
#   - docker push hedleygois/multi-docker-course-client
#   - docker push hedleygois/multi-docker-course-nginx
#   - docker push hedleygois/multi-docker-course-server
#   - docker push hedleygois/multi-docker-course-worker

# # deploy:
# #   provider: elasticbeanstalk
# #   region: 'us-east-1'
# #   app: 'multi-docker'
# #   env: 'MultiDocker-env'
# #   bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
# #   bucket_path: 'docker-multi'
# #   on:
# #     branch: master
# #   access_key_id: $AWS_ACCESS_KEY
# #   secret_access_key: $AWS_SECRET_KEY