language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hedleygois/multi-docker-course -f Dockerfile.dev .

script:
  - docker run hedleygois/multi-docker-course npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-240835633235"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY